# Generated by Django 4.0.3 on 2022-04-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50, null=True)),
                ('show_button', models.BooleanField()),
                ('button_text', models.CharField(max_length=50, null=True)),
                ('button_link', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='media/slider')),
            ],
        ),
    ]
