# Generated by Django 4.0.3 on 2022-04-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_custompage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='show_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='show_services_sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
