# Generated by Django 4.0.3 on 2022-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_custompage_show_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon_markdown', models.CharField(max_length=250)),
                ('hex_icon_color', models.CharField(default='#5c85ce', max_length=10)),
                ('icon_link', models.TextField()),
            ],
        ),
    ]
