# Generated by Django 4.0.3 on 2022-04-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_rename_icon_link_media_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
    ]
