# Generated by Django 4.0.3 on 2022-04-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_slide_caption_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
