# Generated by Django 4.0.3 on 2022-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='show_caption',
            field=models.BooleanField(default=True),
        ),
    ]
