# Generated by Django 4.0.3 on 2022-05-08 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_slide_show_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='special_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
            ],
        ),
    ]
