# Generated by Django 4.0.3 on 2022-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='special_images'),
        ),
        migrations.AddField(
            model_name='special',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
