# Generated by Django 4.0.3 on 2022-05-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_special_image_special_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
